/* 서버 기동시 테이블 등록 */

-- 프로젝트 테이블
CREATE TABLE IF NOT EXISTS PROJECT (
  -- 프로젝트 ID, PRIMARY KEY
  PROJECT_ID  CHAR(36) PRIMARY KEY,
  -- 프로젝트 명칭
  PROJECT_NAME VARCHAR(100) NOT NULL,
  -- 프로젝트 설명
  DESCRIPTION VARCHAR(1000) NOT NULL
);

-- 문서 테이블
CREATE TABLE IF NOT EXISTS DOCUMENT (
  -- 문서 ID, PRIMARY KEY
  DOCUMENT_ID CHAR(36) PRIMARY KEY,
  -- 프로젝트 ID
  PROJECT_ID CHAR(36) NOT NULL,
  -- 문서 유형
  DOCUMENT_TYPE VARCHAR(20) NOT NULL,
  -- 문서 제목
  TITLE VARCHAR(100) NOT NULL,
  -- 저장된 파일명
  FILE_NAME VARCHAR(100) NOT NULL,
  -- 저장된 파일 경로
  FILE_PATH VARCHAR(255) NOT NULL,
  -- 등록일자
  CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_PROJECT_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
);

-- 검색 인덱싱 테이블
CREATE TABLE IF NOT EXISTS SEARCH (
  -- PRIMARY KEY
  SEARCH_ID CHAR(36) PRIMARY KEY,
  -- 프로젝트 KEY
  PROJECT_ID CHAR(36) NOT NULL,
  -- 문서 KEY
  DOCUMENT_ID CHAR(36) NOT NULL,
  -- 색인할 단어(토큰) 또는 키워드
  TOKEN VARCHAR(100) NOT NULL,
  -- 해당 토큰이 문서 내에서 나타나는 순번 또는 위치 값
  POSITION INT NOT NULL,
  
  INDEX IDX_SEARCH_01 (TOKEN),
  INDEX IDX_SEARCH_02 (PROJECT_ID, TOKEN),
  CONSTRAINT FK_SEARCH_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID) ON DELETE CASCADE
);