/* 서버 기동시 테이블 등록 */
CREATE TABLE SEARCH (
  SEARCH_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  DOCUMENT_ID VARCHAR(50) NOT NULL,
  SECTION    VARCHAR(10)  NOT NULL,
  TOKEN      VARCHAR(100) NOT NULL,
  POSITION INT NOT NULL,
  SAMPLE_TITLE VARCHAR(50) NOT NULL,
  SAMPLE_CONTENT VARCHAR(100) NOT NULL,
  INDEX IDX_SEARCH_TOKEN_SECTION (SECTION, TOKEN)
);

CREATE TABLE DOCUMENT_META (
  DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
  FILE_PATH   VARCHAR(255) NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);