/* 서버 기동시 테이블 등록 */

-- 문서 테이블
CREATE TABLE DOCUMENT (
  -- 문서 ID, PRIMARY KEY
  DOCUMENT_ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
  -- 문서 명칭
  DOCUMENT_NAME VARCHAR(100) NOT NULL
);

-- 문서 저장파일 정보
CREATE TABLE DOCUMENT_FILE (
  -- 문서 ID, PRIMARY KEY
  DOCUMENT_ID  BIGINT,
  -- 저장된 파일 경로
  FILE_PATH   VARCHAR(255) NOT NULL,
  -- 등록일자
  CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  CONSTRAINT FK_DOCUMENT_FILE_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID)
);

-- 검색 인덱싱 테이블
CREATE TABLE SEARCH (
  -- PRIMARY KEY
  SEARCH_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  -- 문서 KEY
  DOCUMENT_ID BIGINT NOT NULL,
  -- 색인 구간 구분자 (title 또는 content)
  SECTION    VARCHAR(10)  NOT NULL,
  -- 색인할 단어(토큰) 또는 키워드
  TOKEN      VARCHAR(100) NOT NULL,
  -- 해당 토큰이 문서 내에서 나타나는 순번 또는 위치 값
  POSITION INT NOT NULL,
  -- 목록에 노출될 제목
  TITLE VARCHAR(100) NOT NULL,
  -- 목록에 노출될 일부 내용
  SAMPLE_CONTENT VARCHAR(100) NOT NULL,
  INDEX IDX_SEARCH_TOKEN_SECTION (SECTION, TOKEN),
  CONSTRAINT FK_SEARCH_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID) ON DELETE CASCADE
);